/**
 * GENERATED by `node scripts/build-mcp-catalogue.mjs`. Do not edit by hand.
 *
 * Captured 2026-09-07: 8 services, 8 hosted
 * addresses and 4 programs that run on this computer.
 *
 * **This list is not complete and Atlas has not audited any server on it.** It
 * is a shortcut past typing a package name, nothing more; "By hand" reaches
 * every server that exists. Rows marked `registry` were read from the official
 * MCP Registry, whose metadata is CC0-1.0; rows marked `curated` were read off
 * the vendor's own page on the date beside them.
 *
 * Nothing here is fetched while the app runs. Refreshing it is a person running
 * the script and committing the diff.
 */
import type { CatalogueEntry } from './mcp-catalogue';

/** The day a person ran the generator. The screen says it out loud. */
export const MCP_CATALOGUE_CAPTURED_AT = '2026-09-07';

export const MCP_CATALOGUE: readonly CatalogueEntry[] = [
  {
    "id": "notion",
    "name": "notion",
    "title": "Notion",
    "summary": "Read and write the pages and databases in your Notion workspace.",
    "docsUrl": "https://developers.notion.com/guides/mcp/get-started-with-mcp",
    "verifiedAt": "2026-09-07",
    "registryName": "com.notion/mcp",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.notion.com/mcp",
        "auth": "oauth",
        "headers": [],
        "source": "registry"
      },
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "npx",
        "packageId": "@notionhq/notion-mcp-server",
        "args": [
          "-y",
          "@notionhq/notion-mcp-server"
        ],
        "env": [
          {
            "name": "NOTION_TOKEN",
            "secret": true,
            "required": true,
            "issueUrl": "https://www.notion.so/profile/integrations"
          }
        ],
        "source": "curated"
      }
    ]
  },
  {
    "id": "atlassian",
    "name": "atlassian",
    "title": "Atlassian (Jira · Confluence)",
    "summary": "Read and write Jira issues and Confluence pages in your Atlassian site.",
    "docsUrl": "https://github.com/atlassian/atlassian-mcp-server",
    "verifiedAt": "2026-09-07",
    "registryName": null,
    "registryChecked": false,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.atlassian.com/v2/mcp",
        "auth": "oauth",
        "headers": [],
        "source": "curated"
      }
    ]
  },
  {
    "id": "github",
    "name": "github",
    "title": "GitHub",
    "summary": "Read and write issues, pull requests, code and wikis on GitHub.",
    "docsUrl": "https://github.com/github/github-mcp-server/blob/main/docs/remote-server.md",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.github/github-mcp-server",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://api.githubcopilot.com/mcp/",
        "auth": "oauth",
        "headers": [],
        "source": "registry"
      },
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://api.githubcopilot.com/mcp/readonly",
        "label": "read-only",
        "auth": "oauth",
        "headers": [],
        "source": "curated"
      },
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "docker",
        "packageId": "ghcr.io/github/github-mcp-server",
        "args": [
          "run",
          "-i",
          "--rm",
          "-e",
          "GITHUB_PERSONAL_ACCESS_TOKEN",
          "ghcr.io/github/github-mcp-server"
        ],
        "env": [
          {
            "name": "GITHUB_PERSONAL_ACCESS_TOKEN",
            "secret": true,
            "required": true,
            "issueUrl": "https://github.com/settings/personal-access-tokens/new"
          }
        ],
        "source": "registry"
      }
    ]
  },
  {
    "id": "linear",
    "name": "linear",
    "title": "Linear",
    "summary": "Find, create and update issues, projects and comments in Linear.",
    "docsUrl": "https://linear.app/docs/mcp",
    "verifiedAt": "2026-09-07",
    "registryName": "app.linear/linear",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.linear.app/mcp",
        "auth": "oauth",
        "headers": [],
        "source": "registry"
      }
    ]
  },
  {
    "id": "sentry",
    "name": "sentry",
    "title": "Sentry",
    "summary": "Read errors, issues and debugging data from your Sentry organization.",
    "docsUrl": "https://mcp.sentry.dev/",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.getsentry/sentry-mcp",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.sentry.dev/mcp",
        "auth": "oauth",
        "headers": [],
        "source": "curated"
      }
    ]
  },
  {
    "id": "playwright",
    "name": "playwright",
    "title": "Playwright",
    "summary": "Open web pages and navigate, click, type and read through accessibility snapshots.",
    "docsUrl": "https://github.com/microsoft/playwright-mcp",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.microsoft/playwright-mcp",
    "registryChecked": true,
    "variants": [
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "npx",
        "packageId": "@playwright/mcp",
        "args": [
          "-y",
          "@playwright/mcp"
        ],
        "env": [],
        "source": "registry"
      }
    ]
  },
  {
    "id": "context7",
    "name": "context7",
    "title": "Context7",
    "summary": "Current, version-specific documentation and code examples for a library.",
    "docsUrl": "https://github.com/upstash/context7",
    "verifiedAt": "2026-09-07",
    "registryName": "io.github.upstash/context7",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.context7.com/mcp",
        "auth": "none",
        "headers": [],
        "source": "registry"
      },
      {
        "kind": "local",
        "transport": "stdio",
        "runtime": "npx",
        "packageId": "@upstash/context7-mcp",
        "args": [
          "-y",
          "@upstash/context7-mcp"
        ],
        "env": [
          {
            "name": "CONTEXT7_API_KEY",
            "secret": true,
            "required": false,
            "description": "API key for authentication",
            "issueUrl": "https://context7.com/dashboard"
          }
        ],
        "source": "registry"
      }
    ]
  },
  {
    "id": "supabase",
    "name": "supabase",
    "title": "Supabase",
    "summary": "Query and manage a Supabase project's database, auth, realtime and migrations.",
    "docsUrl": "https://supabase.com/docs/guides/getting-started/mcp",
    "verifiedAt": "2026-09-07",
    "registryName": "com.supabase/mcp",
    "registryChecked": true,
    "variants": [
      {
        "kind": "remote",
        "transport": "http",
        "url": "https://mcp.supabase.com/mcp",
        "auth": "oauth",
        "headers": [],
        "source": "registry"
      }
    ]
  }
] as const;
