// Generated by `pnpm download:release-facts` — do not edit by hand.
//
// Source of truth: the published GitHub Release for the tag below. The
// generator reads each desktop asset's real byte size and download URL, and
// its real SHA-256 from the sibling `.sha256` asset that the release workflow
// uploads. Nothing here is hand-typed, so `/download` can state a size and a
// checksum without inventing either.
//
// `published: false` is the honest pre-release state: the page then says the
// build is not out yet instead of rendering placeholder facts. Re-run the
// generator after the release publishes and commit the result.

export interface MacosReleaseAsset {
  readonly arch: 'aarch64' | 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
}

export interface MacosRelease {
  readonly published: boolean;
  /**
   * Whether this release is a **candidate** rather than a final one. The page says
   * so rather than hiding it: that a build passed the same signing and
   * notarisation path but has not been widely used yet is something the person
   * downloading needs to know beforehand.
   */
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly MacosReleaseAsset[];
}

export interface WindowsReleaseAsset {
  readonly arch: 'x64';
  readonly fileName: string;
  readonly sizeBytes: number;
  readonly sha256: string;
  readonly downloadUrl: string;
  /** Authenticode status verified by the Windows release job. */
  readonly signed: false;
}

export interface WindowsRelease {
  readonly published: boolean;
  readonly prerelease: boolean;
  readonly tag: string;
  readonly publishedAt: string | null;
  readonly releaseUrl: string;
  readonly assets: readonly WindowsReleaseAsset[];
}

export const MACOS_RELEASE: MacosRelease = {
  published: true,
  prerelease: false,
  tag: "v1.1.0",
  publishedAt: "2026-09-08T21:07:56Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.1.0",
  assets: [
    {
      arch: "aarch64",
      fileName: "ontology-atlas_1.1.0_aarch64.dmg",
      sizeBytes: 57686629,
      sha256: "9775fa44da1f774ed167b79ad8df358ea748d24a6c27784a9e66e0e8a4970f2b",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.1.0/ontology-atlas_1.1.0_aarch64.dmg",
    },
    {
      arch: "x64",
      fileName: "ontology-atlas_1.1.0_x64.dmg",
      sizeBytes: 61842877,
      sha256: "008b5165811901c809a11cd0239b75f85d717c2d008fc9cc2f5d17417098597c",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.1.0/ontology-atlas_1.1.0_x64.dmg",
    },
  ],
};

export const WINDOWS_RELEASE: WindowsRelease = {
  published: true,
  prerelease: false,
  tag: "v1.1.0",
  publishedAt: "2026-09-08T21:07:56Z",
  releaseUrl: "https://github.com/wlsdks/ontology-atlas/releases/tag/v1.1.0",
  assets: [
    {
      arch: "x64",
      fileName: "ontology-atlas_1.1.0_windows_x64-setup.exe",
      sizeBytes: 54409841,
      sha256: "6606eb3b89aba063716c80ed70468a7020766202523c5930e291dcc7705c62f0",
      downloadUrl: "https://github.com/wlsdks/ontology-atlas/releases/download/v1.1.0/ontology-atlas_1.1.0_windows_x64-setup.exe",
      signed: false,
    },
  ],
};
