// Generated by scripts/build-mascot-ascii.mjs from the committed mascot masters. Do not edit.
// Source contract: docs/BRAND.md. Regenerate: node scripts/build-mascot-ascii.mjs

/** assets/brand/mascot/mascot-compact-32.png — 14 rows. */
export const MASCOT_ASCII_COMPACT: readonly string[] = [
  "             .**.",
  "             #**'",
  "    .#########..",
  " .###############.",
  ".###\"\"\"\"\"\"\"\"\"\"\"###.",
  "###.............###",
  "###..,,.....,,..###",
  "###..\"#,....\"\"..###",
  "####....\"......####",
  " #################",
  "###########**######",
  "###########**######",
  " '''###########'''",
  "   #####   #####"
];
